services:

    ionic:
      container_name: ionic
      image: ghcr.io/fpalero/poleprojectfrontend:latest
      restart: unless-stopped
      env_file: ./config/.env.ionic
      ports:
        - "8081:80"
      networks:
        - strapi
      depends_on:
        - strapi

    strapi:
      container_name: strapi
      image: ghcr.io/fpalero/poleprojectstrapi-dev:latest
      restart: unless-stopped
      env_file: ./config/.env.strapi
      volumes:
        - public-uploads:/opt/app/public/uploads
      ports:
        - "1337:1337"
      networks:
        - strapi
      depends_on:
        - strapiDB

    strapiDB:
      container_name: strapiDB
      platform: linux/amd64 #for platform error on Apple M1 chips
      restart: unless-stopped
      env_file: ./config/.env.strapi
      image: mariadb:latest
      volumes:
        - strapi-data:/var/lib/mysql
        #- ./data:/var/lib/mysql # if you want to use a bind folder
      ports:
      - "3306:3306"
      networks:
        - strapi
  
    mediawiki:
      image: mediawiki
      container_name: mediawiki
      restart: always
      ports:
        - 8080:80
      links:
        - mediawikiDB
      networks:
        - strapi
      volumes:
        - images:/var/www/html/images
        # After initial setup, download LocalSettings.php to the same directory as
        # this yaml and uncomment the following line and use compose to restart
        # the mediawiki service
        - ./config/LocalSettings.php:/var/www/html/LocalSettings.php
      depends_on:
        - mediawikiDB
    
        # This key also defines the name of the database host used during setup instead of the default "localhost"
    mediawikiDB:
      container_name: mediawikiDB
      image: mariadb
      restart: always
      env_file: ./config/.env.mediawiki
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php 
      volumes:
        - db:/var/lib/mysql
      networks:
        - strapi

volumes:
  public-uploads:
  images:
  db:
  strapi-data:

networks:
  strapi:
    driver: bridge
